import mongoose from 'mongoose';
import dotenv from 'dotenv';

// Models
import User from './models/User.js';
import Artist from './models/Artist.js';
import Album from './models/Album.js';
import Song from './models/Song.js';
import Review from './models/Review.js';
import ReviewReaction from './models/ReviewReaction.js';
import ReviewReply from './models/ReviewReply.js';

// Data
import { userData } from './data/users.js';
import { artistData } from './data/artists.js';
import { albumData } from './data/albums.js';
import { songData } from './data/songs.js';
import { reviewData } from './data/reviews.js';
import { reactionData } from './data/userReactions.js';
import { artistReplyData } from './data/artistReplies.js';

dotenv.config();

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URL);
        console.log("Connected to MongoDB...");
        // Clear existing data
        await User.deleteMany();
        await Artist.deleteMany();
        await Album.deleteMany();
        await Song.deleteMany();
        await Review.deleteMany();
        await ReviewReaction.deleteMany();
        await ReviewReply.deleteMany();

        // Links old ids to new id generated by mongodb
        const idMap = {}; 

        // --- SEED USERS --- //
        console.log("Populating users...");
        await User.insertMany(userData.map(u => {
            const newID = new mongoose.Types.ObjectId();
            idMap[u._id] = newID;
            return {
                ...u, 
                _id: newID, 
                email: u.email || `${u.username}@gmail.com`,
                followers: [],
                following: []
            }
        }));

        // --- SEED ARTISTS --- //
        console.log("Populating artists...");

        for (const a of artistData) {
            const artistObjectId = new mongoose.Types.ObjectId();
            const userObjectId = new mongoose.Types.ObjectId();

            const artistUser = await User.create({
                _id: userObjectId,
                username: a.name.replace(/\s+/g, '').toLowerCase(), // e.g., "Cup Of Joe" -> "cupofjoe"
                email: `${a.name.replace(/\s+/g, '').toLowerCase()}@unsynth.com`,
                password: "password:))",
                role: 'artist', // Important to distinguish them from regular users
                avatar: a.photo,
                bio: a.description
            });

            await Artist.create({
                ...a,
                _id: artistObjectId,
                user: artistUser._id // Link them here
            });

            idMap[a._id] = artistObjectId;
        }

        // --- SEED ALBUMS --- //
        console.log("Populating albums...");
        const createdAlbums = await Album.insertMany(albumData.map(al => {
            const newId = new mongoose.Types.ObjectId();
            idMap[al._id] = newId;
            return { 
                ...al, 
                _id: newId, 
                albumName: al.title,
                artistID: idMap[al.artist_id]
            };
        }));

        // --- SEED SONGS --- //
        console.log("Populating songs...");
        await Song.insertMany(songData.map(s => {
            const newId = new mongoose.Types.ObjectId();
            idMap[s._id] = newId;

            return { 
                ...s, 
                _id: newId,
                songTitle: s.title,
                artistID: idMap[s.artist_id],
                albumID: s.album_id ? idMap[s.album_id] : null 
            };
        }));

        console.log("Linking social connections...");
        for (let u of userData) {
            await User.findByIdAndUpdate(idMap[u._id], {
                followers: u.followers.map(oldId => idMap[oldId]),
                following: u.following.map(oldId => idMap[oldId])
            });
        };

        console.log("Populating Reviews...");
        await Review.insertMany(reviewData.map(r => {
            const newId = new mongoose.Types.ObjectId();
            const userId = idMap[r.user_id]
            const artistId = idMap[r.artist_id];
            const albumId = idMap[r.album_id];
            const songId = idMap[r.song_id];

            const targetId = songId ? songId : albumId;
            const targetType = songId ? 'Song' : 'Album';

            idMap[r._id] = newId;

            return {
                ...r,
                _id: newId,
                user: userId,
                artist: artistId,
                targetID: targetId,
                targetType: targetType
            }
        }));

        console.log("Populating Review Reactions...");
        const reactions = await ReviewReaction.insertMany(reactionData.map(rr => {
            return {
                ...rr,
                user: idMap[rr.user],
                review: idMap[rr.review]
            }
        }))

        console.log("Reactions inserted. Updating counters...");
        const affectedReviews = [...new Set(reactions.map(r => r.review.toString()))]

        for (const id of affectedReviews) {
            await ReviewReaction.updateCounters(id);
        }
        
        console.log("Populating Review Replies...");
        await ReviewReply.insertMany(artistReplyData.map(ar => {
            return {
                ...ar,
                artist: idMap[ar.artist],
                review: idMap[ar.review]
            }
        }))
    
        console.log("Finished populating unsynth database!")
        await mongoose.connection.close(); // Use this instead of process.exit()
        console.log("Connection closed.");
        process.exit(0);
    } catch (err) {
        console.error('Seeding failed:', err);
        process.exit(1);
    }
}

seedData();